const fs = require('fs')
const path = require('path')
const {
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
  createRunOncePlugin,
} = require('@expo/config-plugins')

const RES_NAME = 'network_security_config'

// Lyftr is self-hosted: the backend is usually a LAN box on plain HTTP, or HTTPS with a
// certificate from the owner's own CA installed on their device. Android's release
// defaults block both — cleartext since API 28, user-installed CAs since API 24 — so the
// documented "point the app at http://<lan-ip>:8080" setup cannot work at all (issue #79).
//
// This opts into exactly those two things and nothing else. HTTPS is still fully
// validated (chain, expiry, hostname/SAN); the only change is that the roots the device
// owner deliberately installed also count. It is NOT "ignore certificate errors".
//
// Note this is app-wide rather than scoped to a <domain-config>, which is NOT what Android
// recommends — the guidance is base-config cleartextTrafficPermitted="false" with narrow
// per-domain exceptions. We can't follow it: the server URL is entered by the user at
// runtime and Network Security Config is resolved at build time, so there is no hostname to
// enumerate. Scoping trust to the host the user actually configured needs a runtime
// X509TrustManager (Android) / NSURLSession delegate (iOS) — tracked in #81.
//
// What compensates in the meantime is visibility, since the platform no longer warns for us:
// isInsecureServerUrl in @lyftr/shared drives an amber "Not encrypted" marker on every
// server-URL surface, and the docs lead with HTTPS and treat plain HTTP as an escape hatch.
const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/plugins/withNetworkSecurityConfig.js — do not edit android/ by hand. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
</network-security-config>
`

// Written with a dangerous mod because @expo/config-plugins@54 has no standard mod for
// arbitrary Android resource XML — its only resource writer is withStringsXml, and
// AndroidConfig.Resources exposes no equivalent. Expo's guidance is to prefer standard
// mods and treat dangerous ones as experimental, so the exposure is kept minimal: only
// this file write is dangerous, while the manifest attribute below goes through the
// standard withAndroidManifest. Re-verify the generated output after every SDK upgrade
// (mobile/README.md has the command).
//
// Not using the community expo-network-security-config plugin (~26k downloads/month, MIT,
// actively maintained — a reasonable package). It wraps the same dangerous mod, so it
// removes none of the risk above, and it takes the XML as an external file path, so we
// would still author and own the security-critical content — only the file copy would be
// delegated. Against that: one more dependency, on a single maintainer, sitting on the
// file that governs this app's TLS trust, plus an XML file to keep in sync with app.json.
// Its one genuine improvement over a hand-rolled version is resolving the resource folder
// through the public API instead of hardcoding the path, which is adopted below.
const withConfigFile = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      // Resolve via the public API rather than joining 'app/src/main/res' by hand — that
      // layout is a Gradle convention Expo could change, and this tracks it.
      const xmlPath = await AndroidConfig.Paths.getResourceXMLPathAsync(
        cfg.modRequest.projectRoot,
        { kind: 'xml', name: RES_NAME },
      )
      await fs.promises.mkdir(path.dirname(xmlPath), { recursive: true })
      await fs.promises.writeFile(xmlPath, XML, 'utf8')
      return cfg
    },
  ])

// Without this attribute the res/xml file is inert.
const withManifestAttribute = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    app.$['android:networkSecurityConfig'] = `@xml/${RES_NAME}`
    return cfg
  })

const withNetworkSecurityConfig = (config) => withManifestAttribute(withConfigFile(config))

// No version argument: createRunOncePlugin's dedupe keys on the name alone
// (withRunOnce.js — `getHistoryItem(config, name)`); the version is only recorded in the
// config history and never read. A hardcoded one would be a constant that looks meaningful
// and isn't. The third arg exists for published plugins, which pass their package version.
module.exports = createRunOncePlugin(withNetworkSecurityConfig, 'lyftr-network-security-config')
