const fs = require('fs')
const path = require('path')
const {
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
  createRunOncePlugin,
} = require('@expo/config-plugins')

const RES_NAME = 'network_security_config'

// Lyftr is self-hosted: the backend is usually a LAN box on plain HTTP, or HTTPS with a
// certificate from the owner's own CA installed on their device. Android's release
// defaults block both — cleartext since API 28, user-installed CAs since API 24 — so the
// documented "point the app at http://<lan-ip>:8080" setup cannot work at all (issue #79).
//
// This opts into exactly those two things and nothing else. HTTPS is still fully
// validated (chain, expiry, hostname/SAN); the only change is that the roots the device
// owner deliberately installed also count. It is NOT "ignore certificate errors".
//
// Note this is app-wide rather than scoped to a <domain-config>, which is NOT what Android
// recommends — the guidance is base-config cleartextTrafficPermitted="false" with narrow
// per-domain exceptions. We can't follow it: the server URL is entered by the user at
// runtime and Network Security Config is resolved at build time, so there is no hostname to
// enumerate. Scoping trust to the host the user actually configured needs a runtime
// X509TrustManager (Android) / NSURLSession delegate (iOS) — tracked in #81.
//
// What compensates in the meantime is visibility, since the platform no longer warns for us:
// isInsecureServerUrl in @lyftr/shared drives an amber "Not encrypted" marker on every
// server-URL surface, and the docs lead with HTTPS and treat plain HTTP as an escape hatch.
const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/plugins/withNetworkSecurityConfig.js — do not edit android/ by hand. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
</network-security-config>
`

// @expo/config-plugins has no first-class mod for arbitrary Android resource XML, so the
// file has to be written with a dangerous mod. These run before the regular platform mods,
// so the resource exists by the time the manifest references it.
const withConfigFile = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml')
      await fs.promises.mkdir(xmlDir, { recursive: true })
      await fs.promises.writeFile(path.join(xmlDir, `${RES_NAME}.xml`), XML, 'utf8')
      return cfg
    },
  ])

// Without this attribute the res/xml file is inert.
const withManifestAttribute = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    app.$['android:networkSecurityConfig'] = `@xml/${RES_NAME}`
    return cfg
  })

const withNetworkSecurityConfig = (config) => withManifestAttribute(withConfigFile(config))

module.exports = createRunOncePlugin(
  withNetworkSecurityConfig,
  'lyftr-network-security-config',
  '1.0.0',
)
